apiVersion: apps/v1
kind: Deployment
metadata:
  name: mione-gateway-manager
  namespace: hera-namespace
  labels:
    app: mione-gateway-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mione-gateway-manager
  template:
    metadata:
      labels:
        app: mione-gateway-manager
    spec:
      containers:
      - name: mione-gateway-manager-container
        image: herahub/opensource-pub:mione-gateway-manager-v0.0.2
        resources:
          limits:
            cpu: '500m'
            memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mione-gateway-manager-fe
  namespace: hera-namespace
  labels:
    app: mione-gateway-manager-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mione-gateway-manager-fe
  template:
    metadata:
      labels:
        app: mione-gateway-manager-fe
    spec:
      containers:
      - name: mione-gateway-manager-fe-container
        image: herahub/opensource-pub:mione-gateway-manager-fe-v0.0.1
        resources:
          limits:
            cpu: '500m'
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mione-gateway-manager-fe
  namespace: hera-namespace
  labels:
    app: mione-gateway-manager-fe
spec:
  ports:
    - port: 8077
      targetPort: 8077
      protocol: TCP
  selector:
    app: mione-gateway-manager-fe
  clusterIP: None
