apiVersion: apps/v1
kind: Deployment
metadata:
  name: mione-gateway-manager
  namespace: hera-namespace
  labels:
    app: mione-gateway-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mione-gateway-manager
  template:
    metadata:
      labels:
        app: mione-gateway-manager
    spec:
      containers:
      - name: mione-gateway-manager-container
        image: herahub/opensource-pub:mione-gateway-manager-v0.0.1
        volumeMounts:
          - name: log-path
            mountPath: /home/work/log
        resources:
          limits:
            cpu: '500m'
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mione-gateway-manager
  namespace: hera-namespace
  labels:
    app: mione-gateway-manager
spec:
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app: mione-gateway-manager
  clusterIP: None
